### ISSUE TITLE
Does hugo-classic support single backticks?

### ISSUE THREAD

**Issue by hyperboly** [goodroot/hugo-classic#33]
Normally markdown will render \`foo\` as `foo`, I'm not seeing that in my website. Is this a supported feature? If not, how can I add it?

**Comment by goodroot** [comment]
Hey @hyperboly !

https://github.com/goodroot/hugo-classic/pull/34

This should add the missing style.

Pull down the new repo and/or add the css to resolve!

**Comment by hyperboly** [comment]
Hey thanks.
This works but has some strange unintended effects.

Code blocks will also receive the border
![image](https://github.com/user-attachments/assets/e993fedf-103f-4343-8fda-b06b73d7d1cb)

![image](https://github.com/user-attachments/assets/483ca9bd-7b9e-4de3-9664-c5ff3a36bcb0)
The padding is too big, switching the padding from 1em to 0.1em fixes it.

I modified it to this. I think it will work better? 
```css
code {
    background-color: light-dark(#D6D6D6, #888);
    border-radius: 3px;
    padding: 0.2em;
    overflow-x: auto;
}
```
Looks like this:
![image](https://github.com/user-attachments/assets/486124a2-6855-4537-aca2-cf23d72fb6d1)
